import 'dotenv/config';
import mongoose from 'mongoose';
import Category from '../models/Category.js';
import CategorySection from '../models/CategorySection.js';
import Product from '../models/Product.js';

const SEED_SECTIONS = [
  {
    id: 'sec-structural',
    title: 'Structural & Masonry',
    slug: 'structural-masonry',
    description: 'Foundational building materials direct from factory yards',
    isActive: true,
    categories: ['cat-cement', 'cat-bricks', 'cat-steel', 'cat-sand', 'cat-blocks'],
  },
  {
    id: 'sec-finishing',
    title: 'Finishing & Interiors',
    slug: 'finishing-interiors',
    description: 'Flooring, wall decor, adhesives and surface protection',
    isActive: true,
    categories: ['cat-tiles', 'cat-paints', 'cat-adhesives'],
  },
  {
    id: 'sec-electrical-plumbing',
    title: 'Electrical & Plumbing',
    slug: 'electrical-plumbing',
    description: 'Certified wires, switches, sanitary pipes and water fittings',
    isActive: true,
    categories: ['cat-electrical', 'cat-plumbing'],
  },
];

const SEED_CATEGORIES = [
  {
    id: 'cat-cement',
    name: 'Cement',
    slug: 'cement',
    section: 'Structural & Masonry',
    sectionId: 'sec-structural',
    image: '/images/categories/cat_cement.png',
    description: 'OPC 53 Grade, PPC & Weather-proof construction cement bags',
    subcategories: ['OPC 53 Grade', 'PPC Cement', 'White Cement', 'Waterproof Cement'],
    isActive: true,
  },
  {
    id: 'cat-bricks',
    name: 'Bricks',
    slug: 'bricks',
    section: 'Structural & Masonry',
    sectionId: 'sec-structural',
    image: '/images/categories/cat_bricks.png',
    description: 'Red clay kiln bricks, fly-ash bricks & interlocking pavers',
    subcategories: ['Red Kiln Bricks', 'Fly Ash Bricks', 'Interlocking Pavers'],
    isActive: true,
  },
  {
    id: 'cat-steel',
    name: 'Steel',
    slug: 'steel',
    section: 'Structural & Masonry',
    sectionId: 'sec-structural',
    image: '/images/categories/cat_steel.png',
    description: 'Fe 550D TMT rebar bundles, binding wire & MS angles',
    subcategories: ['8mm TMT Steel', '10mm TMT Steel', '12mm TMT Steel', 'Binding Wire'],
    isActive: true,
  },
  {
    id: 'cat-sand',
    name: 'Sand',
    slug: 'sand',
    section: 'Structural & Masonry',
    sectionId: 'sec-structural',
    image: '/images/categories/cat_sand.png',
    description: 'River sand, M-Sand (manufactured) & plaster sand by dumper',
    subcategories: ['River Sand', 'M-Sand', 'Plaster Sand'],
    isActive: true,
  },
  {
    id: 'cat-blocks',
    name: 'Blocks',
    slug: 'blocks',
    section: 'Structural & Masonry',
    sectionId: 'sec-structural',
    image: '/images/categories/cat_blocks.png',
    description: 'Autoclaved Aerated Concrete (AAC) lightweight blocks & solid blocks',
    subcategories: ['AAC Lightweight Blocks', 'Solid Concrete Blocks', 'Hollow Blocks'],
    isActive: true,
  },
  {
    id: 'cat-tiles',
    name: 'Tiles',
    slug: 'tiles',
    section: 'Finishing & Interiors',
    sectionId: 'sec-finishing',
    image: '/images/categories/cat_tiles.png',
    description: 'Vitrified floor tiles, wall tiles, tile adhesives & epoxy grouts',
    subcategories: ['Vitrified Floor Tiles', 'Ceramic Wall Tiles', 'Tile Adhesive', 'Epoxy Grout'],
    isActive: true,
  },
  {
    id: 'cat-electrical',
    name: 'Electrical',
    slug: 'electrical',
    section: 'Electrical & Plumbing',
    sectionId: 'sec-electrical-plumbing',
    image: '/images/categories/cat_electrical.png',
    description: 'Copper wire rolls, conduit pipes, MCBs & modular switches',
    subcategories: ['Copper Wires (FR-LSH)', 'Conduit Pipes & Boxes', 'Modular Switches & Sockets', 'MCB & Distribution'],
    isActive: true,
  },
  {
    id: 'cat-plumbing',
    name: 'Plumbing',
    slug: 'plumbing',
    section: 'Electrical & Plumbing',
    sectionId: 'sec-electrical-plumbing',
    image: '/images/categories/cat_plumbing.png',
    description: 'CPVC, UPVC pipes, water storage tanks, brass valves & sanitary fittings',
    subcategories: ['CPVC Pipes & Fittings', 'UPVC Drainage Pipes', 'Brass Valves & Cocks', 'Water Storage Tanks'],
    isActive: true,
  },
  {
    id: 'cat-paints',
    name: 'Paints & Wall Finishes',
    slug: 'painting',
    section: 'Finishing & Interiors',
    sectionId: 'sec-finishing',
    image: '/images/products/prod_asian_paints.png',
    description: 'Interior and exterior emulsions, wall putty, and waterproofing solutions',
    subcategories: ['Interior Matt Emulsion', 'Exterior Weatherproof Paint', 'Wall Putty & Primer'],
    isActive: true,
  },
  {
    id: 'cat-adhesives',
    name: 'Adhesives & Chemicals',
    slug: 'adhesives',
    section: 'Finishing & Interiors',
    sectionId: 'sec-finishing',
    image: '/images/products/prod_asian_paints.png',
    description: 'Wood adhesives, instant adhesives, sealants, and waterproofing chemicals',
    subcategories: ['Wood Adhesives', 'Instant Glues', 'Waterproofing Chemicals'],
    isActive: true,
  },
];

const SEED_PRODUCTS = [
  {
    id: 'prod-polycab-wire',
    name: 'Polycab Wire',
    subtitle: '(1.5 sq mm)',
    brand: 'Polycab',
    category: 'Electrical',
    categorySlug: 'electrical',
    section: 'Electrical & Plumbing',
    price: 1250,
    mrp: 2200,
    discountPercent: 43,
    discount: '43% OFF',
    image: '/images/products/prod_polycab.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 150,
    unit: 'roll',
    moq: 1,
    rating: 4.8,
    reviewsCount: 320,
    specifications: {
      'Wire Type': 'FR-LSH (Flame Retardant Low Smoke)',
      'Conductor': '100% Pure Bare Copper',
      'Length': '90 meters roll',
      'Gauge / Size': '1.5 sq mm',
      'Voltage Rating': '1100 V',
    },
    description: 'Polycab FR-LSH Copper Insulated Wire (1.5 sq mm) certified for residential electrification with maximum safety.',
  },
  {
    id: 'prod-asian-paints',
    name: 'Asian Paints',
    subtitle: '(20 L)',
    brand: 'Asian Paints',
    category: 'Paints & Wall Finishes',
    categorySlug: 'painting',
    section: 'Finishing & Interiors',
    price: 3200,
    mrp: 4200,
    discountPercent: 24,
    discount: '24% OFF',
    image: '/images/products/prod_asian_paints.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 85,
    unit: 'bucket',
    moq: 1,
    rating: 4.9,
    reviewsCount: 540,
    specifications: {
      'Finish': 'Smooth Matt Emulsion',
      'Coverage': '130 - 150 sq.ft / litre',
      'Volume': '20 Litres Bucket',
      'Drying Time': '30 minutes to touch',
      'Application': 'Interior Walls',
    },
    description: 'Asian Paints Tractor Emulsion gives interior walls a smart, durable, and rich matt finish at an affordable price.',
  },
  {
    id: 'prod-ultratech-cement',
    name: 'UltraTech Cement',
    subtitle: '(50 kg)',
    brand: 'UltraTech',
    category: 'Cement',
    categorySlug: 'cement',
    section: 'Structural & Masonry',
    price: 340,
    mrp: 415,
    discountPercent: 18,
    discount: '18% OFF',
    image: '/images/products/prod_ultratech.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 500,
    unit: 'bag',
    moq: 10,
    rating: 4.9,
    reviewsCount: 1240,
    specifications: {
      'Grade': 'OPC 53 Grade',
      'Weight': '50 kg HDPE Bag',
      'Compressive Strength': '53 MPa at 28 days',
      'Setting Time Initial': '30 mins minimum',
      'Standard Code': 'IS 269:2015 compliant',
    },
    description: "India's No. 1 Cement for structural foundations, columns, beams, and slabs with ultimate high early compressive strength.",
  },
  {
    id: 'prod-ambuja-cement',
    name: 'Ambuja Plus Cement',
    subtitle: '(50 kg)',
    brand: 'Ambuja',
    category: 'Cement',
    categorySlug: 'cement',
    section: 'Structural & Masonry',
    price: 350,
    mrp: 425,
    discountPercent: 17,
    discount: '17% OFF',
    image: '/images/categories/cat_cement.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 300,
    unit: 'bag',
    moq: 10,
    rating: 4.8,
    reviewsCount: 410,
    specifications: {
      'Grade': 'Special Strength OPC',
      'Weight': '50 kg Bag',
      'Application': 'Reinforced Concrete (RCC)',
    },
    description: 'Ambuja Plus Cement offers dense micro-structure concrete that resists water seepage and enhances structural longevity.',
  },
  {
    id: 'prod-red-kiln-bricks',
    name: 'Red Clay Kiln Bricks',
    subtitle: '(500 Pcs)',
    brand: 'BuildMyDestiny Depot',
    category: 'Bricks',
    categorySlug: 'bricks',
    section: 'Structural & Masonry',
    price: 3950,
    mrp: 4800,
    discountPercent: 18,
    discount: '18% OFF',
    image: '/images/categories/cat_bricks.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 80,
    unit: 'trolley',
    moq: 1,
    rating: 4.7,
    reviewsCount: 180,
    specifications: {
      'Size': '9 x 4.25 x 2.75 inches',
      'Quantity': '500 Pieces per batch',
      'Water Absorption': '< 15%',
      'Crushing Strength': '> 7.5 N/mm²',
    },
    description: 'First-class red kiln-burnt clay bricks with sharp edges, uniform reddish hue, and high compressive load resistance.',
  },
  {
    id: 'prod-fly-ash-bricks',
    name: 'High-Density Fly Ash Bricks',
    subtitle: '(500 Pcs)',
    brand: 'EcoBuild',
    category: 'Bricks',
    categorySlug: 'bricks',
    section: 'Structural & Masonry',
    price: 2900,
    mrp: 3500,
    discountPercent: 17,
    discount: '17% OFF',
    image: '/images/categories/cat_bricks.png',
    isFeatured: false,
    isPopular: true,
    inStock: true,
    stockCount: 120,
    unit: 'trolley',
    moq: 1,
    rating: 4.6,
    reviewsCount: 95,
    specifications: {
      'Size': '230 x 110 x 70 mm',
      'Quantity': '500 Pieces',
      'Finish': 'Smooth Gray Edges',
    },
    description: 'High-precision cement-bonded fly ash bricks requiring 30% less mortar plastering with high thermal insulation.',
  },
  {
    id: 'prod-jindal-steel-12mm',
    name: 'Jindal Panther 550D TMT Steel',
    subtitle: '(12mm Bundle)',
    brand: 'Jindal Steel',
    category: 'Steel',
    categorySlug: 'steel',
    section: 'Structural & Masonry',
    price: 4850,
    mrp: 5800,
    discountPercent: 16,
    discount: '16% OFF',
    image: '/images/categories/cat_steel.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 220,
    unit: 'bundle',
    moq: 1,
    rating: 4.9,
    reviewsCount: 680,
    specifications: {
      'Diameter': '12 mm',
      'Grade': 'Fe 550D Superior Ductility',
      'Standard Length': '12 meters per bar',
      'Corrosion Resistance': 'High (CRS technology)',
    },
    description: 'Primary-grade Jindal Panther TMT rebar bundle with high ductility and superior earthquake resistance.',
  },
  {
    id: 'prod-river-sand-dumper',
    name: 'Washed River Sand',
    subtitle: '(1 Dumper / 300 cu ft)',
    brand: 'Depot Direct',
    category: 'Sand',
    categorySlug: 'sand',
    section: 'Structural & Masonry',
    price: 14500,
    mrp: 17000,
    discountPercent: 15,
    discount: '15% OFF',
    image: '/images/categories/cat_sand.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 35,
    unit: 'dumper',
    moq: 1,
    rating: 4.8,
    reviewsCount: 140,
    specifications: {
      'Volume': '300 cubic feet (1 Dumper Truck)',
      'Silt Content': 'Below 3% (Lab Tested)',
      'Grading': 'Zone II Medium Course Sand',
    },
    description: 'Triple-washed natural river sand ideal for structural RCC slabs, columns, and high-strength mortar plaster.',
  },
  {
    id: 'prod-siporex-aac-blocks',
    name: 'Siporex AAC Lightweight Blocks',
    subtitle: '(600x200x100mm)',
    brand: 'Siporex',
    category: 'Blocks',
    categorySlug: 'blocks',
    section: 'Structural & Masonry',
    price: 68,
    mrp: 85,
    discountPercent: 20,
    discount: '20% OFF',
    image: '/images/categories/cat_blocks.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 2500,
    unit: 'block',
    moq: 100,
    rating: 4.7,
    reviewsCount: 210,
    specifications: {
      'Dimensions': '600 x 200 x 100 mm (4 inch)',
      'Density': '550 - 650 kg/m³',
      'Fire Rating': 'Up to 4 hours',
    },
    description: 'Precision AAC autoclaved aerated blocks offering 50% lighter dead-load, sound insulation, and rapid wall construction.',
  },
  {
    id: 'prod-kajaria-tiles',
    name: 'Kajaria Vitrified Floor Tiles',
    subtitle: '(2x2 ft, Box of 4)',
    brand: 'Kajaria',
    category: 'Tiles',
    categorySlug: 'tiles',
    section: 'Finishing & Interiors',
    price: 1450,
    mrp: 1950,
    discountPercent: 26,
    discount: '26% OFF',
    image: '/images/categories/cat_tiles.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 180,
    unit: 'box',
    moq: 5,
    rating: 4.9,
    reviewsCount: 520,
    specifications: {
      'Size': '600 x 600 mm (2x2 feet)',
      'Box Coverage': '16 sq.ft (4 Tiles)',
      'Finish': 'Polished Glossy Glazed Vitrified',
      'Stain Resistance': 'Nano Polished Class AA',
    },
    description: 'Premium Italian marble veined glazed vitrified floor tiles with scratch resistance and zero water absorption.',
  },
  {
    id: 'prod-havells-wire-25',
    name: 'Havells LifeLine Plus Wire',
    subtitle: '(2.5 sq mm)',
    brand: 'Havells',
    category: 'Electrical',
    categorySlug: 'electrical',
    section: 'Electrical & Plumbing',
    price: 2150,
    mrp: 3100,
    discountPercent: 31,
    discount: '31% OFF',
    image: '/images/products/prod_polycab.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 90,
    unit: 'roll',
    moq: 1,
    rating: 4.9,
    reviewsCount: 430,
    specifications: {
      'Size': '2.5 sq mm',
      'Length': '90 meter standard coil',
      'Type': 'HRFR (Heat Resistant Flame Retardant)',
      'Current Rating': '22 Amperes',
    },
    description: 'Havells 100% Electrolytic Grade Copper Wire certified for heavy appliance loads including air conditioners and geysers.',
  },
  {
    id: 'prod-supreme-cpvc-pipe',
    name: 'Supreme CPVC High Pressure Pipe',
    subtitle: '(1 inch, 3 Meter)',
    brand: 'Supreme',
    category: 'Plumbing',
    categorySlug: 'plumbing',
    section: 'Electrical & Plumbing',
    price: 420,
    mrp: 560,
    discountPercent: 25,
    discount: '25% OFF',
    image: '/images/categories/cat_plumbing.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 350,
    unit: 'pipe',
    moq: 2,
    rating: 4.8,
    reviewsCount: 160,
    specifications: {
      'Size': '1 inch (25 mm) Nominal Bore',
      'Length': '3 Meters (10 ft)',
      'Class': 'SDR 11 (Class 1 - 28.1 bar at 23°C)',
      'Temperature Range': 'Up to 93°C (Hot & Cold Water)',
    },
    description: 'Supreme Lifeline C-PVC hot and cold potable water plumbing pipe with zero bacterial growth and high hydrostatic pressure strength.',
  },
  {
    id: 'prod-fevicol-sh-5kg',
    name: 'Fevicol SH Wood Adhesive',
    subtitle: '(5 kg Bucket)',
    brand: 'Pidilite',
    category: 'Adhesives & Chemicals',
    categorySlug: 'adhesives',
    section: 'Finishing & Interiors',
    price: 980,
    mrp: 1250,
    discountPercent: 22,
    discount: '22% OFF',
    image: '/images/products/prod_asian_paints.png',
    isFeatured: true,
    isPopular: true,
    inStock: true,
    stockCount: 140,
    unit: 'bucket',
    moq: 1,
    rating: 4.9,
    reviewsCount: 780,
    specifications: {
      'Weight': '5 kg Plastic Bucket',
      'Type': 'Synthetic Resin Adhesive',
      'Handling Strength': '6 to 8 hours',
      'Coverage': 'Approx 40 - 45 sq.ft / kg',
    },
    description: "India's most trusted woodworking synthetic adhesive for bonding plywood, laminate sheets, MDF, and wooden furniture.",
  },
];

async function seed() {
  try {
    const mongoUri = process.env.MONGO_URI;
    if (!mongoUri) {
      console.error('MONGO_URI is missing from environment variables');
      process.exit(1);
    }
    console.log('Connecting to MongoDB...');
    await mongoose.connect(mongoUri);
    console.log('Connected successfully!');

    // 1. Seed Category Sections
    console.log('Clearing old Category Sections...');
    await CategorySection.deleteMany({});
    const insertedSections = await CategorySection.insertMany(SEED_SECTIONS);
    console.log(`Seeded ${insertedSections.length} Category Sections!`);

    // 2. Seed Categories
    console.log('Clearing old Categories...');
    await Category.deleteMany({});
    const insertedCats = await Category.insertMany(SEED_CATEGORIES);
    console.log(`Seeded ${insertedCats.length} Categories!`);

    // 3. Seed Products
    console.log('Clearing old Products...');
    await Product.deleteMany({});
    const insertedProds = await Product.insertMany(SEED_PRODUCTS);
    console.log(`Seeded ${insertedProds.length} Products!`);

    console.log('Seeding complete! E-commerce catalog is ready.');
    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err);
    process.exit(1);
  }
}

seed();
